### ISSUE TITLE
Doesn't Work on FS25

### ISSUE THREAD

**Issue by pixelinkmedia** [VertexDezign/RealClock#9]
This mod DOES NOT work on FS25.
Not sure why it is even showing up in FS25.
Looks like there has been no updates since 2-3 years ago.

**Comment by Grisu118** [comment]
You need to be more specific, what does not work?
It works perfeclty for me and multiple other peoples 🤔 

Regarding the no updates, the updates for fs25 were done on a extra branch, I just merged them into the master branch

**Comment by pixelinkmedia** [comment]
It doesn't display on the screen and it doesn't create the XML file

**Comment by pixelinkmedia** [comment]
I downloaded the one from within FS25, and that one works now.
The one I downloaded from Github doesn't work

**Comment by Grisu118** [comment]
As already said, the master branch here was just updated this morning, so I assume you tried to use the fs22 version. Glad that the modhub version works :)
